### ISSUE TITLE
security.txt

### ISSUE THREAD

**Issue by gilbertsoft** [TYPO3/get.typo3.org#110]
Solution for .well-known/security.txt on new hosting environment

@andristeiner

**Comment by ohader** [comment]
See PR #86

**Comment by gilbertsoft** [comment]
@ohader fyi we are going to switch get.t3o to the new server infrastructure and this file will be blocked then because of the security settings on the new server. This was disclosed during the server team sprint and subjects also to other sites ofc. Andri will come up with a solution during next week, this is just a reminder.

**Comment by andristeiner** [comment]
As of now, files within `.well-known` are not blocked anymore.

**Comment by gilbertsoft** [comment]
Great, works fine. Will close this issue now. Thanks @andristeiner
