### ISSUE TITLE
Unable to access Backend Admin

### ISSUE THREAD

**Issue by xandradev** [TYPO3/get.typo3.org#136]
Typo3 v10.3.0 set up has been completed with no errors, but i'm still not able to access Backend admin. I am running xampp v7.2.29. The - http://localhost/typo3_olla/typo3/index.php - file not loading.
![Screenshot (456)](https://user-images.githubusercontent.com/55701047/78251778-be78a100-74e9-11ea-9b1b-d7a2e9d82999.png)
![Screenshot (457)](https://user-images.githubusercontent.com/55701047/78251808-c7697280-74e9-11ea-8799-ee2f769614cb.png)

**Comment by gilbertsoft** [comment]
Hi @xandradev 

This repository is about the TYPO3 download portal at https://get.typo3.org and not for TYPO3 CMS support.

You should post your issue in our Slack channel #typo3-cms or at StackOverflow with the tag TYPO3. To access our Slack workspace go to https://my.typo3.org and register an account or connect your existing one to Slack at https://my.typo3.org/about-mytypo3org/slack

Best regards
Simon
