### ISSUE TITLE
Link missing to previous version in list of changes on release note page

### ISSUE THREAD

**Issue by sypets** [TYPO3/get.typo3.org#142]
https://get.typo3.org/release-notes/4.5.33

![changes](https://user-images.githubusercontent.com/13206455/79306151-05f12b00-7ef5-11ea-982e-18fe2c5e0cd8.png)

I assume that should have been converted to a link.

**Comment by gilbertsoft** [comment]
Related #141

**Comment by gilbertsoft** [comment]
Solved with #411
