### ISSUE TITLE
Major version dates seem to be wrong

### ISSUE THREAD

**Issue by ohader** [TYPO3/get.typo3.org#143]
* https://get.typo3.org/v1/api/major/10
  + `release_date: "2019-07-23T00:00:00+02:00",`
  + actually it's not released yet as LTS
  + seems to be date of v10.0.0
* https://get.typo3.org/v1/api/major/9
  + `release_date: "2018-01-30T00:00:00+01:00",`
  + seems to be date of v9.1.0
* https://get.typo3.org/v1/api/major/8
  + `release_date: "2017-04-04T00:00:00+02:00",`
  + correct date of v8.7.0
* https://get.typo3.org/v1/api/major/7
  + `release_date: "2015-11-10T00:00:00+01:00",`
  + correct date of v7.6.0

I'd suggest to always use the date of the final LTS release - or otherwise refine the models
* first_release_date
* lts_release_date (or just release_date)

**Comment by gilbertsoft** [comment]
v9 is fixed in the database now, will do v10 tomorrow after the LTS release.

I will also check the release scripts to find a final solution here... Afais this date should be updated for each minor release to finally have the correct LTS release date by the release api.

**Comment by gilbertsoft** [comment]
Should all be solved
