### ISSUE TITLE
Template Constants and Setup fields are Unavailable

### ISSUE THREAD

**Issue by superscotty19** [TYPO3/get.typo3.org#148]
Hi,

T3 10.2.2 or 10.3.0, cPanel/centOS install

If I try to edit a template record - or even edit a component of the template like the constants - it begins to load but then the constants and setup textareas disappear and get replaced by unedittable text fields far to the right, offscreen. It's so strange that I can better describe it with a screenshot (attached).

-Scott.
![Screenshot_2020-04-20 SSYO Lightning  TYPO3 CMS 10 3 0](https://user-images.githubusercontent.com/12812378/79828031-1114e280-835d-11ea-9312-32b86de81e61.png)

**Comment by gilbertsoft** [comment]
Hi @superscotty19 

This repository is meant for the download portal of TYPO3 only.

For TYPO3 CMS support please use our Slack workspace or ask your questions at Stackoverflow with the tag `typo3`. Please register for an account and connect it to Slack at https://my.typo3.org/about-mytypo3org/slack.

By the way today is the release of TYPO3 CMS 10.4 LTS which then I would recommend to use.

Best regards
Simon
