### ISSUE TITLE
Fatal Error / missing check of $conf['tags.'] in ContentObjectRenderer.php

### ISSUE THREAD

**Issue by msollmann** [TYPO3/get.typo3.org#158]
PHP Warning: Invalid argument supplied for foreach() in typo3_src-10.4.0/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php line 3934
because of a missing existence check of $conf['tags.']

**Comment by gilbertsoft** [comment]
Hey @msollmann 

This repository is meant for the download portal of TYPO3 only.

For TYPO3 CMS support please use our Slack workspace or ask your questions at Stackoverflow with the tag typo3. Please register for an account and connect it to Slack at https://my.typo3.org/about-mytypo3org/slack.

Best regards
Simon
