### ISSUE TITLE
Support Plattform.Sh as install option

### ISSUE THREAD

**Issue by sbusemann** [TYPO3/get.typo3.org#163]
Dear team,

please provide plattform.sh as install option:

"Deploy with Platform"

Link:
<a href="https://console.platform.sh/projects/create-project/?template=https://github.com/platformsh-templates/typo3&utm_campaign=deploy_on_platform?utm_medium=button&utm_source=affiliate_links&utm_content=https://github.com/platformsh-templates/typo3" target="_blank" title="Deploy with Platform.sh"><img src="https://platform.sh/images/deploy/deploy-button-lg-blue.svg"></a>

This change is supported by the TYPO3 Association

**Comment by gilbertsoft** [comment]
It's already on the start page:
![grafik](https://user-images.githubusercontent.com/25326036/81684968-cff18900-9457-11ea-982e-3a3ed2fc3dab.png)
Afais the version information here should be removed. Any thing else you like to have?

**Comment by bmack** [comment]
Let's use `Try out TYPO3 LTS on platform.sh with one click` as text.

@sbusemann will there be an official maintainer as it is "backed by the TYPO3 Association"? I did this mostly in my spare time as a favor, wasn't meant to maintain this as official... but we can go this way of course.

**Comment by gilbertsoft** [comment]
@sbusemann please review my PR #164

**Comment by gilbertsoft** [comment]
> 
> Let's use `Try out TYPO3 LTS on platform.sh with one click` as text.
> 
tested but one needs about 5 clicks ;)

**Comment by sbusemann** [comment]
@bmack I will try to clarify your question
