### ISSUE TITLE
8 ELTS isn't shown as "E"LTS on the root page

### ISSUE THREAD

**Issue by josefglatz** [TYPO3/get.typo3.org#165]
The place where it is rendered on the homepage: https://github.com/TYPO3/get.typo3.org/blob/5b3a9383ee389edd63692eebbe27426f2770a1c3/templates/default/root.html.twig#L108

![](https://user-images.githubusercontent.com/2861556/81801406-aba7b200-9514-11ea-8714-aa3a1be892ac.png)

**Comment by gilbertsoft** [comment]
Thx for the hint. That's something I have to change manually in the database and I completely forgot it yesterday after the ELTS release. This is already mentioned in #152 to optimize and automate this "renaming".
