### ISSUE TITLE
Delays at TYPO3 backends

### ISSUE THREAD

**Issue by gilbertsoft** [TYPO3/get.typo3.org#169]
See https://forge.typo3.org/issues/91507

There reason is most likely a longer response time of the server in case of high loads. I have requested to get the response times added to the server log for a deeper investigation. Also using Varnish seems to be a good idea.

**Comment by gilbertsoft** [comment]
The reporter of the original ticket contacted me some minutes ago and told me he has currently no issues. So my guess of delays here at the server seems to be true.

**Comment by rafu1987** [comment]
I also think that i.e. a simple `wget --content-disposition https://get.typo3.org/9.5.18` during peek times, seems more unresponsive than usual and before. So this might also be related to high loads on the server side.

**Comment by gilbertsoft** [comment]
After further investigation I saw the blocking of the abusing IP 212.95.122.212 was not longer in place. So I added it again and the server load decreased from 10 down to 0.2 for two CPUs.

**Comment by gilbertsoft** [comment]
The blocking rule was wrong and blocked all pages but the root page. After fixing the configuration issue was here again.
So next step will be to activate the Varnish cache...
