### ISSUE TITLE
Wrong link in release 10.0.0 for release news

### ISSUE THREAD

**Issue by sbusemann** [TYPO3/get.typo3.org#202]
In https://get.typo3.org/release-notes/10.0.0 the link to the release news is wrong. 

Wrong: https://typo3.org/article/x-marks-the-spot-typo3-v100-is-here/

Right: https://typo3.org/article/x-marks-the-spot-typo3-v10-0-is-here

**UAC:**
- [x] Link is corrected to https://typo3.org/article/x-marks-the-spot-typo3-v10-0-is-here

**Comment by gilbertsoft** [comment]
Thanks!
