### ISSUE TITLE
Deeplink to system-requirements

### ISSUE THREAD

**Issue by sbusemann** [TYPO3/get.typo3.org#210]
As an editor, I want to deeplink to the section System Requirements for version of TYPO3

AC:
* id is added to <h2>System Requirements

**Comment by gilbertsoft** [comment]
An anchor is already set but agree would be nice to also a link! The id is `system-requirements`.

E.g. https://get.typo3.org/version/10#system-requirements

**Comment by sbusemann** [comment]
already there - sorry I was blind.
