### ISSUE TITLE
XHR error "405 - Method Not Allowed" on Composer Helper page

### ISSUE THREAD

**Issue by aimcom** [TYPO3/get.typo3.org#212]
I'm currently having a problem with https://get.typo3.org/misc/composer/helper (tested with Firefox 83.0). I get a JavaScript error in the browser console:

```
XHR POST https://get.typo3.org/ajax/composer/helper/generate
[HTTP/2 405 Method Not Allowed 114ms]
```

```
Composer Helper Error: 405 - Method Not Allowed
composerHelper.js:92:25
```

**Comment by gilbertsoft** [comment]
This issue is still pending but for the moment I was able to circumvent it by changing the app_env to staging instead of prod. So far I was not able to reproduce the issue on the staging server nor the local environment.

**Comment by gilbertsoft** [comment]
After more investigation it looks like the PHP-FPM process is terminating unexpected on the production server. I'm also able to reproduce the failure at the second staging server. [This is the line](https://github.com/TYPO3/get.typo3.org/blob/develop/src/Controller/DefaultController.php#L321) which causes the issue and terminates the process. Also putting that line into a try-catch block does not catch the exception but terminates the process and the web server finally reponds with a 405 status. The interesting thing here is also if the context is changed to something else than prod or debugging is activated everything works like expected.
Currently I'm rewriting the composer helper and using a more modern approach for the ajax requests like shown by the current Symfony docs.

**Comment by gilbertsoft** [comment]
> 
> 
> This issue is still pending but for the moment I was able to circumvent it by changing the app_env to staging instead of prod. So far I was not able to reproduce the issue on the staging server nor the local environment.

I had to disable this temporary solution again because it exposes debug infos which is bad on production sites at all.

**Comment by gilbertsoft** [comment]
I have introduced a info box which warns the user about the issue see https://github.com/TYPO3/get.typo3.org/commit/ac27b713c5fe31e57809feddec9cad8e11fdcd3c

**Comment by gilbertsoft** [comment]
After two months of investigation the reason is found. It's the web application firewall which blocked this requests but there was no proper logging pointing to this.

The Composer Helper is back again, I will remove the warning a.s.a.p.

Also I will investigate with the server team for the reason why there was no proper logging for this issue. Normally the WAF logs the related rule ID which was not the case here.

**Comment by gilbertsoft** [comment]
Today we've tried to reproduce the issue again but we were not able to do so. Two days before this issue was opened there was the update to PHP 7.4.13 and on the 11.01.2021 the next one to 7.4.14. So currently it looks like the issue was related to PHP and not WAF.
