### ISSUE TITLE
List in https://get.typo3.org/misc/composer/helper not correct for TYPO3 10

### ISSUE THREAD

**Issue by Padina14** [TYPO3/get.typo3.org#214]
Please remark for TYP3 10 , that the following extesnions are not logger avaiable via composer
//    "typo3/cms-css-styled-content" :  "^10.4",
//    "typo3/cms-documentation" :  "^10.4",
//    "typo3/cms-feedit" : "^10.4",
//    "typo3/cms-func" : "^10.4",
//    "typo3/cms-rsaauth" : "^10.4",
//    "typo3/cms-sys-action" :  "^10.4",
//    "typo3/cms-taskcenter" : "^10.4",

**Comment by gilbertsoft** [comment]
Thanks for the report. Your issue is related to https://github.com/TYPO3/get.typo3.org/issues/212 so I will close this one.
