### ISSUE TITLE
Composer helper doesn't work anymore

### ISSUE THREAD

**Issue by fleischbatzen** [TYPO3/get.typo3.org#229]
It's not possible to get the composer command anymore.
https://get.typo3.org/misc/composer/helper
Get an error on console:
Composer Helper Error: 405 - Method Not Allowed composerHelper.js:92:25
    onreadystatechange https://get.typo3.org/assets/JavaScript/composerHelper.js:92
Best Thorsten

**Comment by gilbertsoft** [comment]
Thanks for your report. I'm going to close your issue in favor of #212
