### ISSUE TITLE
Inconsistent/incorrect end-of-support dates for v9

### ISSUE THREAD

**Issue by schams-net** [TYPO3/get.typo3.org#239]
On [get.typo3.org](https://get.typo3.org/), the end the free support for TYPO3 v9 is listed as `2021-09-01`:

![screenshot001](https://user-images.githubusercontent.com/3617721/115403235-845d6880-a1ec-11eb-86cc-937b05bc77de.png)

The [roadmap at typo3.org](https://typo3.org/cms/roadmap), however, lists the end-of-support as `2021-09-30`:

![screenshot002](https://user-images.githubusercontent.com/3617721/115403447-b1118000-a1ec-11eb-8110-560529199403.png)

**Comment by gilbertsoft** [comment]
Thanks for your hint, the dates are fixed now according the roadmap.
