### ISSUE TITLE
pid not configurable in addRecord TCA

### ISSUE THREAD

**Issue by Make66** [TYPO3/get.typo3.org#246]
TCA select selectMultipleSideBySide addRecord delivers always pid = default=currentPid, so '###SITEROOT###' or 'pid'=>'xx' does not work.
[TCA Documentation](https://docs.typo3.org/m/typo3/reference-tca/10.4/en-us/ColumnsConfig/Type/selectMultipleSideBySide.html#fieldcontrol)
See typo3/sysext/backend/Classes/Form/FieldControl/AddRecord.php:39
Is: 
`$options = $this->data['renderData']['fieldControlOptions'];`
Should be
`$options = $this->data['renderData']['fieldControl']**['addRecord']**;`

Array 'fieldControlOptions' seems never be populated and correct config info is in '['fieldControl'][addRecord]'. Maybe bug is elsewhere but patching this worked for me. 
Use Case: this has to work as documented:
```
'someField' => [
            'exclude' => true,
            'label' => $ll.'.someField',
            'config' => [
                'type' => 'select',
                'renderType' => 'selectMultipleSideBySide',
                'size' => 3,
                'minitems' => 1,
                'fieldControl' => [
                    'addRecord' => [
                        'disabled' => false,
                        'title' => 'addRecordTest for Test',
                        'setValue' => 'set',
                        'pid' => '###SITEROOT###',  // this does not work as documented!!!
                    ],
                    'editPopup' => [
                        'disabled' => false,
                    ],
                ],
                'foreign_table' => 'tx_kurse_domain_model_category',
                'foreign_table_where' =>
                    'AND {#tx_kurse_domain_model_category}.{#pid} IN(###SITEROOT###) '
            ],
        ],
```

**Comment by gilbertsoft** [comment]
@Make66 this repository is about the TYPO3 download portal https://get.typo3.org and not the CMS itself. Please use https://forge.typo3.org to file an issue instead. Thanks!
