### ISSUE TITLE
Issue in upgrade to 11.5.0 from 10.4.21

### ISSUE THREAD

**Issue by GaneshKandu** [TYPO3/get.typo3.org#258]
Hi,

I am getting error while upgrading typo 10.4.21 to 11.5.0

- 1

Fatal error: Declaration of TYPO3\CMS\Extbase\Mvc\Controller\AbstractController::processRequest(TYPO3\CMS\Extbase\Mvc\RequestInterface $request, TYPO3\CMS\Extbase\Mvc\ResponseInterface $response) must be compatible with TYPO3\CMS\Extbase\Mvc\Controller\ControllerInterface::processRequest(TYPO3\CMS\Extbase\Mvc\RequestInterface $request): Psr\Http\Message\ResponseInterface in typo3/sysext/extbase/Classes/Mvc/Controller/AbstractController.php on line 243 

- 2

> (1/2) Doctrine\DBAL\Exception\DriverException

An exception occurred while executing 'UPDATE `be_users` SET `lang` = ? WHERE `uid` = ?' with params ["default", 1]: Data too long for column 'lang' at row 1

in vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/Mysqli/Exception/StatementError.php line 19

```php
            case '1566':
                return new NotNullConstraintViolationException($message, $exception);
        }

        return new DriverException($message, $exception);
    }

    /**
     * {@inheritdoc}
```

> (2/2) Doctrine\DBAL\Driver\Mysqli\Exception\StatementError

Data too long for column 'lang' at row 1

in vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/Mysqli/Exception/StatementError.php line 19

```php
final class StatementError extends MysqliException
{
    public static function new(mysqli_stmt $statement): self
    {
        return new self($statement->error, $statement->sqlstate, $statement->errno);
    }
}
```

getting this issue on ``Upgrade Wizard ``

#### System

PHP 7.4.19 
MySQL 5.7.33
Server version: Apache/2.2.34 (Unix)

**Comment by GaneshKandu** [comment]
I am still getting same issue in upgrade to 11.5.1 from 10.4.21

**Comment by Valkyrion800** [comment]
had the same issue.

mysolution:
typo3 install -> maintenance -> Analyze Database Structure -> search smth with "lang"(can't remember exactly) and select it -> apply

did it work for you?

**Comment by gilbertsoft** [comment]
Thanks for your request. This repository is about the download portal and not TYPO3. Please see https://typo3.org/help on how to get support and also consult the documentation for upgrades at https://docs.typo3.org/m/typo3/guide-installation/11.5/en-us/Major/Index.html.
