### ISSUE TITLE
Streamline Caches

### ISSUE THREAD

**Issue by ohader** [TYPO3/get.typo3.org#290]
## get.typo3.org/11

Scenario: TYPO3 v11.5.6 has been released 30 minutes ago, major version route sill references previous version v11.5.5. At this time the `/json` route already correctly presented version `11.5.6`.

```
curl -I https://get.typo3.org/11
HTTP/1.1 302 Found
Server: nginx
Content-Type: text/html; charset=UTF-8
Content-Length: 502
Connection: keep-alive
Cache-Control: max-age=3600, public
date: Tue, 08 Feb 2022 08:12:01 GMT
location: https://typo3.azureedge.net/typo3/11.5.5/typo3_src-11.5.5.tar.gz
```

## get.typo3.org/json

Caches seem to be updated at least once an hour.

## get.typo3.org/v1/api/major/11/release/latest

More than two hours after the release of `11.5.6`, the release API still shows `11.5.5`.

```
wget --quiet -O - https://get.typo3.org/v1/api/major/11/release/latest | jq -r '.version'
11.5.5
```

## Solution

[`darth` (release script)](https://github.com/typo3/darth) uses a dedicated `announce` command to inform get.typo3.org API that new releases are available. That works find for release notes etc., however not for above mentioned scenarios. It would be great those caches could be updates in the event of having processed new `announce` commands.

**Comment by gilbertsoft** [comment]
Caching was completely rewritten and any issues shoud be solved now. See #344
