### ISSUE TITLE
Changing the download version to 12 leads to 404

### ISSUE THREAD

**Issue by cschnell** [TYPO3/get.typo3.org#320]
When using the "Download" link on https://get.typo3.org/ the result is the page https://get.typo3.org/version/11. 
When switching to version 12 with the dropdown on https://get.typo3.org/version/11 , the result is a 404 page. The dropwdown changes the URL to https://get.typo3.org/version/12
Either the dropdown shouldn't have a 12 option yet or the URL https://get.typo3.org/version/12 should already lead to a valid page.

**Comment by gilbertsoft** [comment]
Thanks for the report. Yes true, the v12 should not be visible at this point but only on the composer helper. Will fix it.
