### ISSUE TITLE
Unable to download TYPO3 packages from get.typo3.org

### ISSUE THREAD

**Issue by ohader** [TYPO3/get.typo3.org#364]
Recent TYPO3 packages cannot be downloaded anymore from get.typo3.org, e.g. https://get.typo3.org/11.5.14.
I guess this is related to fiddling around with https://get.typo3.org/json - which does NOT list TYPO3 versions >= v9 anymore.

Please revert change https://github.com/TYPO3/get.typo3.org/commit/c6d0bdd815340be38c0e9ec21dc2c3d7f0109d15

<img width="1592" alt="Screen Shot 2022-08-17 at 09 46 58" src="https://user-images.githubusercontent.com/402145/185064516-e6785529-8f9f-438d-a7cd-cd8794e1867a.png">

**Comment by gilbertsoft** [comment]
Reverted with https://github.com/TYPO3/get.typo3.org/commit/5d24d22df8669d2781fadfc6e959e47c36aa1f2a. Will look for a working solutions.
