### ISSUE TITLE
Broken download links

### ISSUE THREAD

**Issue by sgmurphy** [TYPO3/get.typo3.org#38]
https://get.typo3.org/json lists the following download URLs, which are broken:

https://get.typo3.org/3.3.0/zip
https://get.typo3.org/3.5.0/zip
https://get.typo3.org/4.5.26rc1/zip
https://get.typo3.org/4.6.0/zip
https://get.typo3.org/4.6.0alpha1/zip
https://get.typo3.org/4.6.0alpha2/zip
https://get.typo3.org/4.6.0alpha3/zip
https://get.typo3.org/4.6.0beta1/zip
https://get.typo3.org/4.6.0beta2/zip
https://get.typo3.org/4.6.0beta3/zip
https://get.typo3.org/4.6.0rc1/zip
https://get.typo3.org/4.6.18/zip
https://get.typo3.org/4.7.0alpha1/zip
https://get.typo3.org/4.7.0alpha2/zip
https://get.typo3.org/4.7.0alpha3/zip
https://get.typo3.org/4.7.0beta1/zip
https://get.typo3.org/4.7.0beta2/zip
https://get.typo3.org/4.7.0beta3/zip
https://get.typo3.org/4.7.0rc1/zip
https://get.typo3.org/4.7.0rc2/zip
https://get.typo3.org/4.7.11rc1/zip
https://get.typo3.org/6.0.0alpha1/zip
https://get.typo3.org/6.0.0alpha2/zip
https://get.typo3.org/6.0.0alpha3/zip
https://get.typo3.org/6.0.0beta1/zip
https://get.typo3.org/6.0.0beta2/zip
https://get.typo3.org/6.0.0rc1/zip
https://get.typo3.org/6.0.0rc2/zip
https://get.typo3.org/6.0.5rc1/zip
https://get.typo3.org/6.1.0alpha1/zip
https://get.typo3.org/6.1.0beta1/zip
https://get.typo3.org/6.1.0beta2/zip
https://get.typo3.org/6.1.0rc1/zip
https://get.typo3.org/6.2.0alpha1/zip
https://get.typo3.org/6.2.0alpha2/zip
https://get.typo3.org/6.2.0alpha3/zip
https://get.typo3.org/6.2.0beta1/zip
https://get.typo3.org/6.2.0beta2/zip
https://get.typo3.org/6.2.0beta3/zip
https://get.typo3.org/6.2.0beta4/zip
https://get.typo3.org/6.2.0beta5/zip
https://get.typo3.org/6.2.0beta6/zip
https://get.typo3.org/6.2.0beta7/zip
https://get.typo3.org/6.2.0rc1/zip
https://get.typo3.org/6.2.0rc2/zip
https://get.typo3.org/6.2.10rc1/zip
https://get.typo3.org/7.6-snapshot-20160223/zip
https://get.typo3.org/8.7-snapshot-20170404/zip

**Comment by zaudles** [comment]
OK
