### ISSUE TITLE
Documentation for DDEV Local and TYPO3 12.0.0 does not work / install

### ISSUE THREAD

**Issue by akiessling** [TYPO3/get.typo3.org#386]
Hi,

i wanted to try out the new release with my local ddev setup, but had multiple errors that prevented me to install it.

https://get.typo3.org/version/12

> ddev config --project-type=typo3 --docroot=public --create-docroot

I updated to the current version of ddev (1.21.1) and this created a PHP 8.0 config, but 8.1 is required according to the docs.

> ddev composer create --no-install "typo3/cms-base-distribution:^12"
> ddev composer install

This worked, although it ran with PHP 8.0

> ddev typo3cms install:setup

tyypo3_console is not installed with this setup and not ready for TYPO3 12.0
https://github.com/TYPO3-Console/TYPO3-Console/issues/1075

I switched to the web installer, first message is that PHP 8.1 is required.
> Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.1.0". You are running 8.0.21. in /var/www/html/vendor/composer/platform_check.php on line 24

Updating to PHP 8.1 is no problem thanks to ddev and then the installer worked, i had to enter the db credentials etc. and was good to go.

When i tested this on a slightly older ddev setup, it created a PHP 7.4 config and MariaDB had a strange/different identifier. Thus the installer thought i was running MySQL 5.5 although i was using MariaDB 10.3 and 10.5 --> it failed the requirements check.

It would be good to add a hint that you should upgrade to the most current version (or at least 1.21.1)

**Comment by martin-git-kristensen** [comment]
What database credentials do you used - I tried with ddev: db and db - but I couldn't get typo3 to accept it?

**Comment by akiessling** [comment]
Did you change the host also to db? It runs in an extra container, not the same one as PHP.

So: 
User = db
Pass = db
Host = db

**Comment by gilbertsoft** [comment]
Thanks for your report. I'm already on a patch for DDEV to get it all running again.

**Comment by akiessling** [comment]
Thanks for taking care!

**Comment by gilbertsoft** [comment]
For the time being you can use the following procedure:

```
ddev config --project-type=typo3 --docroot=public --create-docroot --php-version 8.1
ddev composer create --no-install "typo3/cms-base-distribution:^12"
ddev composer install
ddev config --auto
ddev exec mkdir -p config/system
ddev exec cp public/typo3conf/AdditionalConfiguration.php config/system/additional.php
ddev exec touch public/FIRST_INSTALL
ddev launch
```

**Comment by martin-git-kristensen** [comment]
A ha - I was using 127.0.0.1 as host - I will try with db as well. Thanks for the tip.

**Comment by gilbertsoft** [comment]
A new DDEV build fixing the issues is available at https://github.com/drud/ddev/pull/4268#issuecomment-1271532128. Update your local binary and use the following commands:

```
ddev config --project-type=typo3 --docroot=public --create-docroot --php-version 8.1
ddev composer create --no-install "typo3/cms-base-distribution:^12"
ddev composer install
ddev config --auto
ddev exec touch public/FIRST_INSTALL
ddev launch
```

The final DDEV release is planed to be done later today....

**Comment by martin-git-kristensen** [comment]
I can get ddev ver 1.21.1 to deliver php 8.1 - BUT when I try to install typo3 with composer it stops and says that my php is only 7.4.3. Very strange. I upload a phpinfo.php file and in the browser it says php 8.1 ???

**Comment by akiessling** [comment]
This is getting a bit offtopic @martin-git-kristensen  ;) You configured .ddev/config to use PHP 8.1? 
> php_version: "8.1"

What is the output when you run this command? 
```
ddev exec php --version
```

It should print something like  `PHP 8.1.8 (cli) (built: Jul 11 2022 08:55:24) (NTS)`
Did you use the commands from https://github.com/TYPO3/get.typo3.org/issues/386#issuecomment-1271336414?

Thanks @gilbertsoft for fixing ddev - these are quite some breaking changes and now it makes sense that TYPO3 12 did not pick up the autogenerated AdditionalConfiguration.php :)

**Comment by martin-git-kristensen** [comment]
It prints PHP 8.1.8 (cli) (built: Jul 11 2022 08:55:24) (NTS) allright but when composer says that php is only 7.4.3 when I try to install typo3 v12 with composer?

**Comment by gilbertsoft** [comment]
> It prints PHP 8.1.8 (cli) (built: Jul 11 2022 08:55:24) (NTS) allright but when composer says that php is only 7.4.3 when I try to install typo3 v12 with composer?

Please tell more about what exactly you are doing, show the commands you are using....

**Comment by martin-git-kristensen** [comment]
OK - when I follow this it actually works :-) 
ddev config --project-type=typo3 --docroot=public --create-docroot --php-version 8.1
ddev composer create --no-install "typo3/cms-base-distribution:^12"
ddev composer install
ddev config --auto
ddev exec touch public/FIRST_INSTALL
ddev launch

I was using the helper https://get.typo3.org/misc/composer/helper to fetch the 12 version and then my composer got the php version all wrong. 
Thanks for your patience.

**Comment by gilbertsoft** [comment]
> OK - when I follow this it actually works :-) ddev config --project-type=typo3 --docroot=public --create-docroot --php-version 8.1 ddev composer create --no-install "typo3/cms-base-distribution:^12" ddev composer install ddev config --auto ddev exec touch public/FIRST_INSTALL ddev launch
> 
> I was using the helper https://get.typo3.org/misc/composer/helper to fetch the 12 version and then my composer got the php version all wrong. Thanks for your patience.

I hardly guess you called just `composer ...` and not `ddev composer ...`. Always run the commands in the container with DDEV to avoid version conflicts ;)

**Comment by gilbertsoft** [comment]
The temporary instructions are deployed now, so closing this issue.
