### ISSUE TITLE
MariaDB 10.6

### ISSUE THREAD

**Issue by gmuley** [TYPO3/get.typo3.org#392]
Is it possible to use Typo3 v10, v11 or v12 with MariaDB 10.6? Maybe MariaDB 10.6 client and MariaDB 10.2 server, is that supported? MariaDB is listed only up to <= 10.5.99!

**Comment by bmack** [comment]
we're currently only testing until MariaDB 10.5, however I think I have 10.6 running with TYPO3 v11. will check with the other core mergers.

**Comment by gmuley** [comment]
Hi Benny,
thank you for the quick answer and in advance for testing!

**Comment by bmack** [comment]
Hi @gmuley ,

just another quick update: We're currently running our test suite in v11+v12 with MariaDB 10.6, so no problems here.

**Comment by gilbertsoft** [comment]
The requirements are changed for v11 and v12.

**Comment by gmuley** [comment]
Thank you very much for the quick response guys 👍

**Comment by gmuley** [comment]
Hi Benni,


sorry, me again... is it also possible to use v10 with MariaDB 10.6?

Do you have any empirical values here?

 
 

Gesendet: Montag, 17. Oktober 2022 um 09:46 Uhr
Von: "Benni Mack" ***@***.***>
An: "TYPO3/get.typo3.org" ***@***.***>
Cc: "Günny" ***@***.***>, "Mention" ***@***.***>
Betreff: Re: [TYPO3/get.typo3.org] MariaDB 10.6 (Issue #392)


 

Hi @gmuley ,

just another quick update: We're currently running our test suite in v11+v12 with MariaDB 10.6, so no problems here.

**Comment by bmack** [comment]
I do not have empirical values. But I tested a v10 project of mine which I upgraded from MariaDB 10.3 to 10.6 without any problems.
