### ISSUE TITLE
[BUG] Frontend user login through pi based plugin no more possible (T3 v10, since 10.4.33)

### ISSUE THREAD

**Issue by SadikAtMNM** [TYPO3/get.typo3.org#401]
Login via pi based plugin login forms is not possible any more. The commit [https://github.com/typo3/typo3/commit/96ed3e627f](https://github.com/typo3/typo3/commit/96ed3e627f) introduced the signed storage pid list only for the extbased forms.
Solution for me was to add
`protected function getSignedStorageFolders(): string
{
  $pidList = $this->spid;
  return sprintf(
            '%s@%s',
            $pidList,
            GeneralUtility::hmac($pidList, \TYPO3\CMS\Frontend\Authentication\FrontendUserAuthentication::class)
            );
    }`
to TYPO3\CMS\Felogin\Controller\FrontendLoginController and replace `$this->spid` in the class functions by a call to that function (`$this->getSignedStorageFolders()`)

**Comment by ohader** [comment]
→ see https://review.typo3.org/c/Packages/TYPO3.CMS/+/77119
