### ISSUE TITLE
Update to version 11.5.21 - ERRORS

### ISSUE THREAD

**Issue by anatol06** [TYPO3/get.typo3.org#402]
Hi!
I updated today the Typo3 website from 11.5.19 to version 11.5.21. it was successful. The Front End works but in backend a lot of problems, many pages are not available. Trying to open pages from backend menu, the backend disappeared completely. I had to login in back end from another browser in order to get it back. Then, it disappeared in in this browser as well. I had to return to the old version   11.5.19.  In the back end Logs there where a lot of errors.

**Comment by gilbertsoft** [comment]
Hi @anatol06 , thanks for your report. This repository is about the TYPO3 download portal and not the TYPO3 CMS. Please use https://forge.typo3.org instead. Thanks.
