### ISSUE TITLE
Update PHP 8.2 support

### ISSUE THREAD

**Issue by DanielSiepmann** [TYPO3/get.typo3.org#403]
PHP 8.2 is officially supported: https://typo3.org/article/announcing-official-php-82-support-for-current-typo3-versions
But get.typo3.org still doesn't mention PHP 8.2 compatibility:
![image](https://user-images.githubusercontent.com/354250/211252215-6c2ac563-a9bb-4e26-bf19-fb2a869f8c30.png)

Would be cool if this could be updated.

**Comment by ohader** [comment]
Thanks for pointing this out. PHP 8.2 support now is mentioned for TYPO3 v11 and v12 as well on https://get.typo3.org/

<img width="1148" alt="Screenshot 2023-01-09 at 08 54 42" src="https://user-images.githubusercontent.com/402145/211262054-19d88092-a742-421b-ba25-842d77f258e5.png">

**Comment by DanielSiepmann** [comment]
That was fast, thank you @ohader
