### ISSUE TITLE
add PHP-Version in V10 DDEV-instructions

### ISSUE THREAD

**Issue by rtoenjes** [TYPO3/get.typo3.org#404]
In the [Set up a new V10 project via DDEV and Composer](https://get.typo3.org/version/10#accordion-ddev) I recommend adding a `--php-version=7.4` because DDEV uses PHP8.0 by default. In V12 there is already something similar.

**Comment by gilbertsoft** [comment]
Thanks for the hint! Change will be deployed to production later this day...
