### ISSUE TITLE
TYPO3 11/12 LTS with MariaDB 10.11.x

### ISSUE THREAD

**Issue by urz-hgw** [TYPO3/get.typo3.org#410]
Hi,

currently the requirements for TYPO3 11 LTS and 12 are set for MariaDB <= 10.9.99.

In the upcoming Debian 12 it looks like MariaDB will be shipped in version 10.11.2. Will this version be supported by TYPO3 11 LTS and the upcoming 12 LTS as well?

Best regards
Daniel

**Comment by georgringer** [comment]
see https://github.com/TYPO3/typo3/commit/d869e957432d895c183844f31446131bec623483. the versions are currently tested and it seems those will be supported as well

**Comment by gilbertsoft** [comment]
Requirements are updated for versions 10-12
