### ISSUE TITLE
Previous releases not linked anymore in changelog

### ISSUE THREAD

**Issue by ohader** [TYPO3/get.typo3.org#411]
see e.g. https://get.typo3.org/release-notes/12.3.0#changes

<img width="1071" alt="Screenshot 2023-03-28 at 12 24 43" src="https://user-images.githubusercontent.com/402145/228207454-dc7fb82b-f4ee-426b-b763-0ba9cda9a4e5.png">

**Comment by gilbertsoft** [comment]
Here is what I get from the release process:

```
Here is a list of what was fixed since
[12.2.0](TYPO3_CMS_12.2.0 "wikilink"):
```

These old wiki links get removed during the rendering I guess since ever. But should be easy to replace by a valid release link instead. Will have a look...

**Comment by ohader** [comment]
Probably related to markdown link rendering - and the false positives that occurred in the past, when e.g. trying to render `[BUGFIX]` from the commit subject.

**Comment by gilbertsoft** [comment]
No, the link gets just removed at the moment. Have to figure out how to replace the link properly.

https://github.com/TYPO3/get.typo3.org/blob/develop/src/Twig/Extension/ReleaseNotesExtension.php#L44
