### ISSUE TITLE
Change label for version 10 to ELTS in Composer Helper

### ISSUE THREAD

**Issue by NeoBlack** [TYPO3/get.typo3.org#422]
The version in marked as LTS but is ELTS at the moment, see screenshot below

![Bildschirmfoto 2023-07-10 um 10 41 57](https://github.com/TYPO3/get.typo3.org/assets/1128085/77e445a7-c8ff-4ed1-a351-37aa42e732dc)

**Comment by gilbertsoft** [comment]
Fixed in the database.
