### ISSUE TITLE
"Check for Core Updates" Button does not work with versions upt to 12.4.4

### ISSUE THREAD

**Issue by erru0000** [TYPO3/get.typo3.org#424]
When trying to check for an update with this button in TYPO3, nothing happens. No checking. All settings are correctly set! It did work before with version 11.
When clicking the button, the console says:

Uncaught Unknown update action "undefined"

initialize https://xyz.com/typo3/sysext/install/Resources/Public/JavaScript/module/upgrade/core-update.js?bust=ba8a4bf4f84bbf3b18aaf3d1df49e57c650ad19e:13
    jQuery 2
        dispatch
        handle

**Comment by ohader** [comment]
This issue has been fixed with TYPO3 v12.4.5 → see https://forge.typo3.org/issues/100865 for details
