### ISSUE TITLE
Add PHP 8.3 as supported PHP versions for TYPO3 v12 and v11

### ISSUE THREAD

**Issue by sgrossberndt** [TYPO3/get.typo3.org#428]
# Problem:

Inconsistency between several pages regarding the PHP compatibility to PHP 8.3 for TYPO3 v12 and v11:

https://typo3.org/cms/roadmap#section-php-compatibility-chart lists
- PHP 8.1, 8.2, 8.3 as supported versions for TYPO3 v12
- PHP 7.4, 8.0, 8.1, 8.2, 8.3 as supported versions for TYPO3 v11

https://get.typo3.org/ lists
- `PHP 8.1, 8.2` as system requirements for TYPO3 v12
- `PHP 7.4, 8.0, 8.1, 8.2` as system requirements for TYPO3 v11

https://get.typo3.org/version/12#system-requirements also says PHP 8.3 is supported: `PHP >= 8.1.0 <= 8.3.99`

https://get.typo3.org/version/11#system-requirements lists `PHP >= 7.4.1 <= 8.2.99` as system requirement

# TODO:
- https://get.typo3.org/ should be updated and list PHP 8.3 as supported version for both TYPO3 v11 and v12
- https://get.typo3.org/version/11#system-requirements should be updated and list  `PHP >= 7.4.1 <= 8.3.99` as system requirement

**Comment by bmack** [comment]
We only need to update this line FYI https://github.com/TYPO3/get.typo3.org/blob/develop/src/Twig/Extension/RequirementExtension.php#L103
