### ISSUE TITLE
files not updated when uploading files with spaces in filename via backend upload, even when option "overwriting"

### ISSUE THREAD

**Issue by erru0000** [TYPO3/get.typo3.org#438]
When uploading a file with space in filename via backend upload, TYPO3 changes spaces in filename into underlines.
When uploading a changed version with the same name (with spaces!), TYPO3 asks as normal if it should overwrite the filename and does so. However, the file is NOT updated then, it remains the same old version of the file.
e.g. 
"this is testfile.pdf" is changed into "this_is_testfile.pdf" and if I upload a changed version of this file with "this is testfile.pdf", the old version remains on server through the process of renaming it with underlines.
When I upload with the renamed filename "this_is_testfile.pdf", TYPO3 correctly overwrites the file on server. It just does not overwrite when it has to change spaces into underlines...

This is a problem for editors as they very often do not think of giving filenames without spaces in the name... And they are getting problems when trying to update but TYPO3 doesn't as it should.

I hope it is clear what I mean, not everybody understands the problem here...

**Comment by andreaskienast** [comment]
If this is a bug in TYPO3, please report it over at https://forger.typo3.com. This repository holds the website get.typo3.org, not related to TYPO3 Core.
