### ISSUE TITLE
Fix DDEV instructions to install TYPO3 v13

### ISSUE THREAD

**Issue by JaccoBeech** [TYPO3/get.typo3.org#439]
Correct instructions at https://get.typo3.org/version/13

```
ddev config --project-type=typo3 --docroot=public --create-docroot.
ddev composer create --no-install "typo3/cms-base-distribution:^13"
ddev composer install
ddev typo3cms install:setup
```

Results in

`typo3cms: command not found`

**Comment by andreaskienast** [comment]
Thank you for your report. Your issue has been solved already with #434 but wasn't deployed, yet.
