### ISSUE TITLE
Release note pages: markdown not converted into a proper link

### ISSUE THREAD

**Issue by schams-net** [TYPO3/get.typo3.org#47]
Introduction sentence in section **Changes** on release notes shows Markdown syntax that is not converted into a proper link.

![screenshot-20190821-1037](https://user-images.githubusercontent.com/3617721/63393799-1e5d8400-c400-11e9-8453-9bea460d45dd.png)

This problem occurs on all release note pages.  
For example: https://get.typo3.org/release-notes/9.5.9

**Comment by ohader** [comment]
Introduced in commit 89ec877fb5156ff220dbd4ac6bfc82f0f2818caf - kind of a chicken-egg problem in order to not (theoretical) XSS through Git log subjects...
