### ISSUE TITLE
Missing "maintained_until" and "elts_until" data leads to a failure of some MaintenanceWindow functions

### ISSUE THREAD

**Issue by svewap** [TYPO3/get.typo3.org#473]
For example in https://get.typo3.org/api/v1/major/12

The methods isSupportedByCommunity and isSupportedByElts therefore return false, which breaks the update notification.

**Comment by benjaminkott** [comment]
resolved with https://github.com/TYPO3/get.typo3.org/commit/01e6a12c046987668bd06d0e3c7e65f0ed090fe3
