### ISSUE TITLE
Fix misleading MariaDB version

### ISSUE THREAD

**Issue by schams-net** [TYPO3/get.typo3.org#50]
Reported by Benjamin Amir on [Slack](https://typo3.slack.com/archives/C024TUMM7/p1568104058175900):

> [sic!] _Hi All, im watching at typo3 8.7 requirments on typo3.org and im a bit confused about mariadb version: is it 10.0.26 or 10.1.26 or 10.2.26?_

![image](https://user-images.githubusercontent.com/3617721/64600345-46884380-d3fe-11e9-8091-ffcb08334ca0.png)

This is on page <https://get.typo3.org/version/8>

**Comment by liayn** [comment]
Correct value is "10.2.26"

**Comment by hsrwebmaster** [comment]
I dont think 10.2.26 is right. I think the dot is missing between 2 and 6. 
10.2.6 is the version before mariadb decided to implement a fix that fuck's up the db compare with the double quote issue.

https://forge.typo3.org/issues/82023
https://jira.mariadb.org/browse/MDEV-13132

**Comment by ohader** [comment]
* 10.2.6 seems to be correct (thx @hsrwebmaster for pointing to the forge issue)
* model currently supports `float` only (https://github.com/TYPO3-infrastructure/get.typo3.org/blob/master/src/Entity/Requirement.php#L73)
* adjusted value to `10.3` for the time being

**Comment by hsrwebmaster** [comment]
Just for verification this double quote problem ist solved for mariadb 10.3?

https://forge.typo3.org/issues/82023

**Comment by hsrwebmaster** [comment]
Sorry but it is a bit confusing because now on get.typo3.org it say's that 8.7 support's MariaDB 10.3

![2019-09-11 15_38_04-Download TYPO3](https://user-images.githubusercontent.com/48752857/64704642-e69da580-d4ae-11e9-9df8-3c5a46e2014d.png)

**Comment by gilbertsoft** [comment]
Is now fixed

**Comment by Naled** [comment]
Is there a reason why MariaDB 10.4 is not in the support list?

From the changelog there where "only" System/Performence improvements nothing related to SQL language also no Incompatibilities are listed.

https://mariadb.com/kb/en/mariadb-vs-mysql-compatibility/

Other CMS like Shopware etc.. are listing MariaDB 10.3 or greater ...
