### ISSUE TITLE
Add version option for composer helper

### ISSUE THREAD

**Issue by saenglert** [TYPO3/get.typo3.org#51]
The [composer helper](https://get.typo3.org/misc/composer/helper) is really great to get all the necessary packages at one. However, it is not possible to select which version should be used. With the recent sprint releases simple copy and paste installs version 10. To install LTS 9 I have to manually add `:^9` behind every package and IMHO this defeats the purpose of having this tool in the first place (One click stop to get all composer requirements).

So my feature request: Please add a dropdown that lets me select the version of TYPO3 to be installed and adjust the composer command according to input. Versions should include LTS and sprints.

Cheers

**Comment by astehlik** [comment]
I really like the idea! Although I'm not sure if adding `:^9` after every package is the way to go.

I'm using a different approach in my `composer.json` files. I only add a version number to the `typo3/minimal` minimal requirement and add all other packages with a wildcard version requirement:

```json
{
	"require": {
		"typo3/minimal": "^9.5.0",

		"typo3/cms-adminpanel": "*",
		"typo3/cms-fluid-styled-content": "*",
		"...": "*"
 	}
}
```

This allows me to change the version at one place and run `composer update`. The other packages are updated automatically by Composer's dependency resolving.

Maybe we could add "typo3/minimal" with the selected version in the Composer helper?

Cheers, Alex

**Comment by saenglert** [comment]
@tmotyl Thank you very much for your PR.
One small improvement: Updating the version dropdown should also update the composer command. Currently, only clicking the installation type (`full`, `minimal`, `default` or `reset`) triggers an update.
