### ISSUE TITLE
Decorate version information with DQUOTEs in composer helper generator

### ISSUE THREAD

**Issue by e-geisler** [TYPO3/get.typo3.org#75]
Executing "composer require typo3/cms-core:^9.5" from the Windows commandline leads to some obscure error messages regarding to version dependencies. I worked around this issue by embedding the version informations in double quotes. AFAIK '^' is treated as special character by the commandline interpreter.

**Comment by helhum** [comment]
In other words:

Current output: `composer require typo3/cms-core:^9.5`
Desired output: `composer require "typo3/cms-core:^9.5"`

Rationale: The current command works on *nix, but not Windows, the proposed command works on all systems.

**Comment by e-geisler** [comment]
This works on Windows too:
composer require typo3/cms-core:"^9.5"
